# Generated by Django 3.2.3 on 2021-05-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='image_protudo',
            new_name='image_produto',
        ),
    ]
