# Generated by Django 3.2.3 on 2021-05-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_rename_image_protudo_produto_image_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='image_produto',
            field=models.ImageField(blank=True, null=True, upload_to='produto<built-in function id>/'),
        ),
    ]
