# Generated by Django 3.2.3 on 2021-05-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_image_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='image_produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='produto-<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='produto-<django.db.models.fields.CharField>/'),
        ),
    ]
