# Generated by Django 3.2.3 on 2021-05-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20210522_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='produto-<django.db.models.fields.CharField>/'),
        ),
    ]
