# Generated by Django 3.2.3 on 2021-05-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('cart', '0003_rename_produtos_carrinho_total_por_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='produtos',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='produtos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
    ]
