# Generated by Django 3.2.3 on 2021-05-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210519_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='total_por_produto',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='total_por_produto',
            field=models.ManyToManyField(blank=True, null=True, to='cart.ItemPedido'),
        ),
    ]
