# Generated by Django 3.2.3 on 2021-05-19 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('cart', '0005_auto_20210519_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='total_por_item',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produtos',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
            preserve_default=False,
        ),
    ]
