# Generated by Django 3.2.3 on 2021-05-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20210519_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='produtos',
            new_name='produto',
        ),
    ]
