# Generated by Django 3.2.3 on 2021-05-19 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('cart', '0007_rename_produtos_itempedido_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='descontos',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='total_por_produto',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='total_por_produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.itempedido'),
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='produto',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='produto',
            field=models.ManyToManyField(blank=True, to='produto.Produto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='total_por_item',
            field=models.FloatField(default=0),
        ),
    ]
