# Generated by Django 3.2.3 on 2021-05-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20210519_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinho',
            old_name='total_por_produto',
            new_name='produtos',
        ),
    ]
