# Generated by Django 3.2.3 on 2021-05-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('cart', '0011_rename_itempedido_itemcarrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrinho',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
    ]
