# Generated by Django 3.2.3 on 2021-05-22 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_cupomdesconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='cupom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cupomdesconto'),
        ),
    ]
