# Generated by Django 3.2.3 on 2021-05-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_cupomdesconto_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
    ]
