# Generated by Django 3.2.3 on 2021-05-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_carrinho_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
