# Generated by Django 3.2.3 on 2021-05-24 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Em processamento', max_length=12)),
                ('cod_pagamento', models.CharField(blank=True, max_length=14, null=True)),
                ('valor_total', models.FloatField(default=0.0)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costumer.costumer')),
            ],
        ),
    ]
