# Generated by Django 3.2.3 on 2021-05-24 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0017_carrinho_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=order.models.generate_code, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('deposit', 'Depósito'), ('pagseguro', 'PagSeguro'), ('paypal', 'PayPal')], default='deposit', max_length=20, verbose_name='opção de pagamento')),
                ('valor_total', models.FloatField(default=0.0)),
                ('all_produtos', models.ManyToManyField(blank=True, to='cart.ItemCarrinho')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
