# Generated by Django 3.2.3 on 2021-05-24 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_carrinho_subtotal'),
        ('order', '0002_alter_order_comprador'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='produtos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.itemcarrinho'),
            preserve_default=False,
        ),
    ]
