# Generated by Django 3.2.3 on 2021-05-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_carrinho_total'),
        ('order', '0008_auto_20210524_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('deposit', 'Depósito'), ('pagseguro', 'PagSeguro'), ('paypal', 'PayPal')], default='deposit', max_length=20, verbose_name='opção de pagamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='all_produtos',
            field=models.ManyToManyField(blank=True, to='cart.ItemCarrinho'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Aguardando Pagamento'), (1, 'Pagamento Aprovado'), (2, 'Em separação'), (3, 'Concluida'), (4, 'Cancelada')], default=0, verbose_name='Situação'),
        ),
    ]
