# Generated by Django 3.2.3 on 2021-05-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210524_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_pagamento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
