# Generated by Django 3.2.3 on 2021-05-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
